<script setup lang="ts">
import { computed } from 'vue'
import { Globe, LayoutDashboard, Paintbrush, ShieldAlert } from 'lucide-vue-next'
import { useRoute, useRouter } from 'vue-router'
import { useDashboardStore } from '@/stores/dashboard.store'
const route = useRoute(); const router = useRouter(); const dashboard = useDashboardStore()
const editorPath = computed(() => dashboard.data?.homePage ? `/editor/${dashboard.data.homePage.id}` : null)
const publicPath = computed(() => dashboard.data?.website.subdomain ? `/site/${dashboard.data.website.subdomain}` : null)
function go(path: string, _role?: 'school' | 'admin'): void { void router.push(path) }
</script>
<template><header class="sticky top-0 z-40 w-full border-b border-slate-800 bg-slate-900 text-xs text-slate-200 shadow-md"><div class="mx-auto flex h-10 max-w-7xl items-center justify-between gap-3 px-3 sm:px-6"><div class="flex items-center gap-2"><span class="flex items-center gap-1.5 font-semibold tracking-wide text-white"><span class="h-2 w-2 animate-pulse rounded-full bg-emerald-400"/>Edusite Platform</span><span class="hidden text-slate-500 sm:inline">•</span><span class="hidden items-center gap-1 rounded bg-slate-800 px-2 py-0.5 text-[11px] text-slate-400 sm:inline-flex">Tenant: <strong class="font-medium text-white">{{ dashboard.data?.website.fullDomain ?? '—' }}</strong></span></div><nav class="flex items-center gap-1 overflow-x-auto py-1"><button class="flex items-center gap-1.5 whitespace-nowrap rounded-md px-2.5 py-1" :class="route.path.startsWith('/dashboard') ? 'bg-sky-600 text-white' : 'hover:bg-slate-800'" @click="go('/dashboard','school')"><LayoutDashboard class="h-3.5 w-3.5"/>User Dashboard</button><button :disabled="!editorPath" class="hidden items-center gap-1.5 rounded-md px-2.5 py-1 hover:bg-slate-800 disabled:cursor-not-allowed disabled:opacity-40 sm:flex" @click="editorPath && go(editorPath,'school')"><Paintbrush class="h-3.5 w-3.5 text-amber-300"/>Visual Editor</button><button class="hidden items-center gap-1.5 rounded-md px-2.5 py-1 hover:bg-slate-800 md:flex" @click="go('/admin','admin')"><ShieldAlert class="h-3.5 w-3.5"/>Admin Portal</button><button :disabled="!publicPath" class="hidden items-center gap-1.5 rounded-md px-2.5 py-1 hover:bg-slate-800 disabled:cursor-not-allowed disabled:opacity-40 lg:flex" @click="publicPath && go(publicPath)"><Globe class="h-3.5 w-3.5 text-emerald-300"/>Live Public Site</button></nav></div></header></template>
